### ISSUE TITLE
role system planning?

### ISSUE THREAD

**Issue by coolzilj** [prest/prest#197]
Is there role system planning just like PostgREST?

**Comment by felipeweb** [comment]
@coolzilj Today it is not possible to do like postgREST because the db is global for pREST, but i think  we can implement a simple role system based on JWT token data. I really like the ideia  that pREST have simple role system. 

What do you think about it @avelino @lerrua @cassiobotaro @marioidival @crgimenes @gtsalles ?

**Comment by crgimenes** [comment]
I like the ideia

**Comment by lerrua** [comment]
Sounds good to me, we can put this idea on the next roadmap.

**Comment by korc** [comment]
This is a showstopper feature for me. Without it, it's not possible to expose prest to the real web, unless you use it only for `SELECT` operation on access-limited, fully public tables. Kinda defeats the purpose..
There have to be some way to implement something like `SET ROLE` based on JWT attributes.

**Comment by hjelmeland** [comment]
So would it be possible to implement sending `SET ROLE` based on some predefined JWT attributes? Any reason why it should not work? Any coding tips in case I want to try to code it my self?

We need it for the project I am working on now. The alternative is to throw out pREST and make our own API.
