### ISSUE TITLE
restructuring for use of more than one database adapter

### ISSUE THREAD

**Issue by joelmdesouza** [prest/prest#213]
Hello everyone

I use the MySQL database.
I would like to restructure the pRest project to support other database adpaters in addition to Postgres.

I implemented the restructuring on a fork and will run all the tests as it appears in CONTRIBUTING.md.

After that, can I send the PRs for analysis?
Basically they are used to change the direct calls of postegres for calls of the new interface Adapter.

This is my first contribution to open-source, so if you're doing something wrong, please excuse me and correct me.

**Comment by crgimenes** [comment]
@felipeweb, @cassiobotaro, @marioidival what do you guys think?

**Comment by marioidival** [comment]
SGTM

**Comment by felipeweb** [comment]
SGTM

**Comment by joelmdesouza** [comment]
I finish the first step to make the pREST compatible with more than one Adapter.
Changes were made to the following packages:
-adapters
-config
-controllers
-middlewares

I ran tests of all project packages, including unchanged ones.
Can I send the PRs for analysis?
I wanted this analysis before I started implementing the MySQL Adapter.

Note:
Probably there will be more changes in some package besides adapters to support MySQL, I think I will have to change the statements package, however this will be done as needed.

**Comment by joelmdesouza** [comment]
A doubt.
Do PR of the prest package with the vendor updated with these changes?

**Comment by felipeweb** [comment]
Yes  of course

Em ter, 12 de set de 2017 às 17:44, Joel M. de Souza <
notifications@github.com> escreveu:

**Comment by joelmdesouza** [comment]
done the PRs, in each repository

**Comment by joelmdesouza** [comment]
I uploaded the requested changes.
I ran all the tests except in the controllers package.
I run the tests in the controllers package on Linux, later or tomorrow, it does not work right in bash git in Windows, something related to the path of queries.

**Comment by joelmdesouza** [comment]
I ran all tests.
All PASS.

**Comment by felipeweb** [comment]
@joelmdesouza  could you send a pull request on  main repo just add postgres.Load(). without update vendor?

**Comment by fabriziomello** [comment]
Hi all, 

First of all sorry because I'm too late in this thread but I'll share my thoughts:
- Shouldn't we have a config for adapters instead to have it hard coded? (I'm starting by understand about pREST internals so maybe this ask make no sense)
- What about create anoter environment variable like PREST_ADAPTER={postgresql|mysql|sqlite}
- Thinking more about to have new adapters we need to think if is feasible to have configs like it: PREST_DB_HOST, PREST_DB_USER, ... we should maintain old PREST_PG_?? for backward compatibility
- And what about URI connections, i.e.:  adapter://user:pass@host:port/database?option=value??

**Comment by felipeweb** [comment]
* I particularly like de idea that use hardcoded adapters because we don't need add  some code to detect adapter on prest and if people want to implement adapter for some new database and is possible, just using prest as framework, but is not prest maintainer responsibility to know about the other new database

* I like the ideia that remove PG prefix.

What the do you think about it @crgimenes @avelino @lerrua @cassiobotaro @marioidival @gtsalles  ?

**Comment by joelmdesouza** [comment]
There will still be changes in the configuration part.
But my idea is to implement the MySQL adapter, making the least amount of changes at the first moment.
During the implementation of the MySQL adapter we will have a better idea of all the points that will need refactoring for the total independence of each adapter.
