### ISSUE TITLE
Operations in batch

### ISSUE THREAD

**Issue by felipeweb** [prest/prest#295]
pREST need to support operations in batch

TODO
- [x] Insert
- [ ] Update

**Comment by felipeweb** [comment]
- [x] Insert
- [ ] Update

**Comment by cassiobotaro** [comment]
Although the merge of this functionality has already been done, I would like to raise some points that should be discussed.
Initially I will raise some points regarding insertion but they may be extended to other batch operations.

As we are working on a REST api, I believe the status code returned by this operation should be 201 since we are creating new features.

Another point is the content returned in response to this batch insert operation. Other frameworks similar to pREST like postgrest adopt a blank response. It makes sense when you think of inserting a large number of records.

One more point is the implementation of the insertion itself, it can be optimized using the COPY command and as can be seen in this [proof of concept](https://gist.github.com/cassiobotaro/c06e6c03945e61e102145a6c963da73f), we have a considerably high gain.

![31229315_402444700228267_751788064719765504_n](https://user-images.githubusercontent.com/3127847/39284432-960ba678-48e9-11e8-9be1-df2c6395afd4.jpg)

This picture shows two endpoints ,`batch` that is an  endpoint using multiple values in insert(`insert into ...values (...), (...), (...)`) and `batchi` that uses copy. Tests are made for 10000 records.

We should also discuss what happens when the insertion of one of the records fails. Should we rollback the entire transaction? Did we ignore that record?

I would like the opinion of other maintainers before proceeding with the implementation of batch operations.

**Comment by marioidival** [comment]
> As we are working on a REST api, I believe the status code returned by this operation should be 201 since we are creating new features.

you're right.

> Another point is the content returned in response to this batch insert operation. Other frameworks similar to pREST like postgrest adopt a blank response. It makes sense when you think of inserting a large number of records.

I agree

> We should also discuss what happens when the insertion of one of the records fails. Should we rollback the entire transaction? Did we ignore that record?

I suggest make a test using psql directly and see what's happens there.

**Comment by felipeweb** [comment]
> As we are working on a REST api, I believe the status code returned by this operation should be 201 since we are creating new features.

you're right.

> Another point is the content returned in response to this batch insert operation. Other frameworks similar to pREST like postgrest adopt a blank response. It makes sense when you think of inserting a large number of records.

I  believe that is import returning the array of inserted rows, but use `RETURNING` with `COPY` is impossible for now PostgreSQL doesn't support it, so although the multi values haven't better performance we can implement using multi values yet, because we have possibilities to use `RETURNING`

> We should also discuss what happens when the insertion of one of the records fails. Should we rollback the entire transaction? Did we ignore that record?

I suggest make a test using psql directly and see what's happens there.

**Comment by kemelzaidan** [comment]
+1 for the 201 status code.

I believe the whole point here is:

1. having more performance but sacrificing return data or...
2.  ...be less performant in order to have the return.

Most people that uses pRest (including us) use it to query the DB from the frontend. This whole feature came up because we needed to execute batch operations (in our case, dealing with multiple files on Nufs) from the frontend. So, it's important to know if the return value is absolutely necessary. Because of that, I think @heltonalves99 should be listened on this issue.

_Another option_, since we're talking about a 10x faster gain with COPY would be **implementing both operations** and **choosing between then with a flag or an attribute**. By doing this, the frontend would choose between the two possibilities: if I only need to delete multiple files, I can do that fast without caring for the return; otherwise if I'm doing another operation, the return can be important.

**Comment by heltonalves99** [comment]
For the 201 status, it's the most appropriate!

What about the return! I believe in some cases the full return will be important and some cases it will not matter.

I think 10k transactions with this execution time as @cassio showed to us, this no problem. I was trying to image a case that a user will do more than 10k transactions at once, maybe it can be rarely.
In the most case, the software needs to know whats happened with the transactions to handle with it show a aproppriate response. As will be here at Nuveo, the application needs to show the user if each transaction was ok or happened any error.

I don't know about the implementation complexbility, but to have both feature could be good ideia!

**Comment by cassiobotaro** [comment]
After discuss we decide to implement both cases. See two PR's above. Next steps are implement batch update and document these new features.

**Comment by cassiobotaro** [comment]
Batch insertion was implemented using values and copy (best for many records) as can be seen in the PR's above.
The batch update, although it was [drafted](https://gist.github.com/cassiobotaro/0999e201825969129fcec12fc28a03b9), was not implemented because in discussion with the project maintainers, it was inefficient in terms of performance.
More discussion at prest chat on telegram.
