### ISSUE TITLE
prest looses database context during concurrent calls

### ISSUE THREAD

**Issue by inv2004** [prest/prest#497]
**prest looses current database context if you make several requests to different database-names (on one instance)**

**To Reproduce**
To catch the datarace-condition it would be better to insert if database == "db1" { Sleep(3*time.Second) } before runQuery in controllers/tables.go:

1) Run query1 to db1/tbl1
2) Run query2 to db2/tbl2
3) query 1 returns data
3s sleep
4) query1 fails with error because 2nd step made setDataBase("db2")

**Expected behavior**
Everything works. PR to demonstrate fix: https://github.com/prest/prest/pull/496

**Additional context**
This PR just to demonstrate the problem and hotfix we applied. I suppose it is necessary to rework the patch if you want to accept into master: probably to not pass SQL like string, but to create a structure with content which will contain database name and SQL.

Also: The patch fixes just select race-conditions, but not insert and some other cases

**Comment by inv2004** [comment]
@nkolster is added to watch the issue

**Comment by arxdsilva** [comment]
Hi @inv2004, we might add #584 as a small fix for this. Wont solve the problem but we want to give more flexibility over the multiple DB setup, so you wont need to share the same host/username/password on multiple databases in the same API. I'm not sure how It'll be done since its still to be discussed, but might get a rework on config files and a new middleware that helps the query swap between databases in a more secure way without needing to change the API.

In v2 we'll possibly make a new API that doesn't need this big of a change to be versatile.
