### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by pandrian75** [prest/prest#536]
CockroachDB support will be great!
Pierre A.

**Comment by avelino** [comment]
discussion related to this subject
https://github.com/prest/prest/discussions/387#discussioncomment-108952

**Comment by arxdsilva** [comment]
@pandrian75 
just to clarify: we want to focus on Postgres, but since cockroachDB is focused on pgsql, there should be no problem using both together. 

If you come to any problems by using this combination let us know and we'll map when we decide to add more DB support. For me at least cockroachDB is a high priority in the upcoming DBs as it allows us to give more flexibility to users.
