### ISSUE TITLE
Docker Image Build Failing

### ISSUE THREAD

**Issue by vmesel** [prest/prest#734]
```
Successfully tagged ghcr.io/prest/prest:latest
The push refers to repository [ghcr.io/prest/prest]
803fc9354a89: Preparing
9176014dec8d: Preparing
3ffd6b7b9[188](https://github.com/prest/prest/actions/runs/3420694804/jobs/5695843123#step:16:189): Preparing
6f0ca1bcc562: Preparing
1ed5d83a1818: Preparing
fbbb8386c9be: Preparing
c77c007a46fa: Preparing
86bbc29e949d: Preparing
3a8d602e51a3: Preparing
d1dec9917839: Preparing
d38adf39e1dd: Preparing
4ed121b04368: Preparing
d9d07d703dd5: Preparing
86bbc29e949d: Waiting
fbbb8386c9be: Waiting
c77c007a46fa: Waiting
3a8d602e51a3: Waiting
d1dec9917839: Waiting
d38adf39e1dd: Waiting
d9d07d703dd5: Waiting
unauthorized: unauthenticated: User cannot be authenticated with the token provided.
4ed121b04368: Waiting
Error: Process completed with exit code 1.
```

Docker image build is failing on the master branch due to an invalid token.

**Comment by vmesel** [comment]
@avelino @arxdsilva what do we need to do in order to solve this?

**Comment by arxdsilva** [comment]
@vmesel ill have a look tomorrow at the credentials and give you an update.

**Comment by avelino** [comment]
Problem fixed ([here](https://github.com/prest/prest/commit/a4953ba73d28295d76a8f90aea611bb8666aae92)):
- docker image generated in [docker hub](https://hub.docker.com/layers/prest/prest/v1.1.6/images/sha256-90932282e387a9edec071b1298551e7feac1200deab5ef62ec06d2263f552557?context=explore)
- docker image generated in [github packages](https://github.com/prest/prest/pkgs/container/prest/63272063?tag=v1.1.6)
- goreleaser generating the [release in github](https://github.com/prest/prest/releases/tag/v1.1.6)

I will close this issue because it was run ["Build Failing"](https://github.com/prest/prest/actions/runs/3908056055/jobs/6677873490), but I will open a new issue to simplify and split the build and release process.

> sorry for coupling this build so much in the past

cc @vmesel @arxdsilva @cuducos
